import type { FollowupItem } from "./model";

export const MOCK_FOLLOWUPS: FollowupItem[] = [
  {
    id: 1,
    text: "Tedarikçi ile sözleşme şartları yeniden müzakere edilecek.",
    topic_id: 1,
    responsible_person_id: 1,
    responsible_person_name: "Ahmet Yılmaz",
    responsible_company_id: null,
    responsible_company_name: undefined,
    due_date: "2026-09-15",
    status: "OPEN",
    waiting_reason: "",
    blocker_item_id: null,
    completed_on: null,
    development_note: "",
    version: 1,
    bucket: "OVERDUE",
    source_meeting_id: 1,
    source_meeting_title: "2026 Q3 Stratejik Planlama",
    source_meeting_date: "2026-09-22",
    created_at: "2026-09-22T09:00:00Z",
    updated_at: "2026-09-22T09:00:00Z",
    change_log: [
      { id: 1, timestamp: "2026-09-22T09:00:00Z", user_name: "Ahmet Yılmaz", action: "CREATE", description: "Takip konusu oluşturuldu." },
      { id: 2, timestamp: "2026-09-22T14:30:00Z", user_name: "Ahmet Yılmaz", action: "UPDATE", field: "due_date", old_value: "2026-09-20", new_value: "2026-09-15", description: "Termin tarihi güncellendi." },
    ],
  },
  {
    id: 2,
    text: "İş güvenliği eğitim programı taslağı hazırlanacak.",
    topic_id: 2,
    responsible_person_id: 3,
    responsible_person_name: "Mehmet Kaya",
    responsible_company_id: 2,
    responsible_company_name: "Anadolu",
    due_date: "2026-09-18",
    status: "IN_PROGRESS",
    waiting_reason: "",
    blocker_item_id: null,
    completed_on: null,
    development_note: "Eğitim modülleri hazırlanıyor, içerik onay aşamasında.",
    version: 2,
    bucket: "TODAY",
    source_meeting_id: 2,
    source_meeting_title: "Sprint 14 Retrospektif",
    source_meeting_date: "2026-09-25",
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-09-20T10:00:00Z",
    change_log: [
      { id: 1, timestamp: "2026-09-20T10:00:00Z", user_name: "Mehmet Kaya", action: "CREATE", description: "Takip konusu oluşturuldu." },
      { id: 2, timestamp: "2026-09-21T11:15:00Z", user_name: "Mehmet Kaya", action: "UPDATE", field: "status", old_value: "Açık", new_value: "Sürüyor", description: "Durum güncellendi." },
      { id: 3, timestamp: "2026-09-22T09:45:00Z", user_name: "Mehmet Kaya", action: "UPDATE", field: "development_note", old_value: "", new_value: "Eğitim modülleri hazırlanıyor", description: "Gelişme notu eklendi." },
    ],
  },
  {
    id: 3,
    text: "UX ekibi yeni onboarding prototipini sunacak.",
    topic_id: 3,
    responsible_person_id: 2,
    responsible_person_name: "Elif Demir",
    responsible_company_id: null,
    responsible_company_name: undefined,
    due_date: "2026-09-25",
    status: "OPEN",
    waiting_reason: "",
    blocker_item_id: null,
    completed_on: null,
    development_note: "",
    version: 1,
    bucket: "SOON",
    source_meeting_id: 3,
    source_meeting_title: "Müşteri Geri Bildirim",
    source_meeting_date: "2026-09-18",
    created_at: "2026-09-18T14:00:00Z",
    updated_at: "2026-09-18T14:00:00Z",
    change_log: [
      { id: 1, timestamp: "2026-09-18T14:00:00Z", user_name: "Elif Demir", action: "CREATE", description: "Kaynak bağlantısı eklendi · toplantı #3" },
      { id: 2, timestamp: "2026-09-18T17:54:00Z", user_name: "Elif Demir", action: "UPDATE", field: "responsible_person", old_value: "", new_value: "Elif Demir", description: "Toplantı notundan takibe alındı · toplantı #101" },
    ],
  },
  {
    id: 4,
    text: "Ar-Ge bütçe artış talebinin üst yönetime sunulması.",
    topic_id: 4,
    responsible_person_id: 1,
    responsible_person_name: "Ahmet Yılmaz",
    responsible_company_id: null,
    responsible_company_name: undefined,
    due_date: "2026-10-15",
    status: "OPEN",
    waiting_reason: "",
    blocker_item_id: null,
    completed_on: null,
    development_note: "",
    version: 1,
    bucket: "LATER",
    source_meeting_id: 1,
    source_meeting_title: "2026 Q3 Stratejik Planlama",
    source_meeting_date: "2026-09-22",
    created_at: "2026-09-22T09:30:00Z",
    updated_at: "2026-09-22T09:30:00Z",
    change_log: [
      { id: 1, timestamp: "2026-09-22T09:30:00Z", user_name: "Ahmet Yılmaz", action: "CREATE", description: "Takip konusu oluşturuldu." },
    ],
  },
  {
    id: 5,
    text: "ISO 27001 politika dokümanları güncellendi ve onaylandı.",
    topic_id: 5,
    responsible_person_id: 4,
    responsible_person_name: "Zeynep Arslan",
    responsible_company_id: null,
    responsible_company_name: undefined,
    due_date: "2026-09-10",
    status: "DONE",
    waiting_reason: "",
    blocker_item_id: null,
    completed_on: "2026-09-10",
    development_note: "",
    version: 3,
    bucket: "CLOSED",
    source_meeting_id: 4,
    source_meeting_title: "Bilgi Güvenliği Komite",
    source_meeting_date: "2026-09-10",
    created_at: "2026-09-10T09:00:00Z",
    updated_at: "2026-09-12T11:00:00Z",
    change_log: [
      { id: 1, timestamp: "2026-09-10T09:00:00Z", user_name: "Zeynep Arslan", action: "CREATE", description: "Takip konusu oluşturuldu." },
      { id: 2, timestamp: "2026-09-10T16:00:00Z", user_name: "Zeynep Arslan", action: "UPDATE", field: "status", old_value: "Açık", new_value: "Tamamlandı", description: "Durum güncellendi." },
    ],
  },
  {
    id: 6,
    text: "Aylık kalite kontrol raporunun yönetim kuruluna sunulması.",
    topic_id: null,
    responsible_person_id: 3,
    responsible_person_name: "Mehmet Kaya",
    responsible_company_id: null,
    responsible_company_name: undefined,
    due_date: null,
    status: "OPEN",
    waiting_reason: "Kalite verilerinin tamamlanması bekleniyor",
    blocker_item_id: null,
    completed_on: null,
    development_note: "",
    version: 1,
    bucket: "NO_DATE",
    source_meeting_id: 2,
    source_meeting_title: "Sprint 14 Retrospektif",
    source_meeting_date: "2026-09-25",
    created_at: "2026-09-25T10:00:00Z",
    updated_at: "2026-09-25T10:00:00Z",
    change_log: [
      { id: 1, timestamp: "2026-09-25T10:00:00Z", user_name: "Mehmet Kaya", action: "CREATE", description: "Takip konusu oluşturuldu." },
    ],
  },
];
